#!/usr/bin/env bash
# Bootstrap Warwick Bethel Retreat production wiring (local helper).
# Usage:
#   cp .env.deploy.example .env.deploy
#   # Fill in NEON_DATABASE_URL, VERCEL_* from dashboards
#   ./scripts/bootstrap-warwick-production.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_ENV="$ROOT/.env.deploy"
RETREAT_DIR="$ROOT"

red() { echo "❌ $*"; }
green() { echo "✅ $*"; }
yellow() { echo "⚠️  $*"; }

if [[ ! -f "$DEPLOY_ENV" ]]; then
  red "Missing $DEPLOY_ENV — copy from .env.deploy.example and fill values."
  exit 1
fi

# shellcheck disable=SC1090
source "$DEPLOY_ENV"

echo "=== Warwick Bethel Retreat — production bootstrap ==="
echo ""

# ─── 1. Local retreat .env for development against production API ───
if [[ -n "${RENDER_API_URL:-}" ]]; then
  cat > "$RETREAT_DIR/.env.local.production" <<EOF
# Generated by bootstrap-warwick-production.sh — do not commit
NEXT_PUBLIC_API_BASE_URL=${RENDER_API_URL}
INTERNAL_API_URL=${RENDER_API_URL}
NEXT_PUBLIC_APP_URL=${VERCEL_PRODUCTION_URL:-http://localhost:3000}
NEXT_PUBLIC_APP_NAME=Warwick Bethel Retreat
EOF
  green "Wrote .env.local.production"
else
  yellow "Set RENDER_API_URL in .env.deploy"
fi

# ─── 2. Vercel link file (skip broken CLI link) ───
if [[ -n "${VERCEL_PROJECT_ID:-}" && -n "${VERCEL_ORG_ID:-}" ]]; then
  mkdir -p "$RETREAT_DIR/.vercel"
  cat > "$RETREAT_DIR/.vercel/project.json" <<EOF
{
  "projectId": "${VERCEL_PROJECT_ID}",
  "orgId": "${VERCEL_ORG_ID}"
}
EOF
  green "Wrote .vercel/project.json"
else
  yellow "Set VERCEL_PROJECT_ID and VERCEL_ORG_ID in .env.deploy (Vercel → Project Settings)"
fi

# ─── 3. Vercel env pull via token (bypasses OIDC if corporate network blocks link) ───
if [[ -n "${VERCEL_TOKEN:-}" && -f "$RETREAT_DIR/.vercel/project.json" ]]; then
  (cd "$RETREAT_DIR" && npx vercel env pull .env.vercel.production.local --environment production --yes --token "$VERCEL_TOKEN") \
    && green "Pulled Vercel production env" \
    || yellow "vercel env pull failed — set vars in Vercel dashboard instead"
elif [[ -z "${VERCEL_TOKEN:-}" ]]; then
  yellow "Set VERCEL_TOKEN in .env.deploy for CLI env pull"
fi

# ─── 4. Vercel deploy via token ───
if [[ -n "${VERCEL_TOKEN:-}" && -f "$RETREAT_DIR/.vercel/project.json" ]]; then
  echo ""
  read -r -p "Deploy to Vercel production now? [y/N] " ans
  if [[ "${ans,,}" == "y" ]]; then
    (cd "$RETREAT_DIR" && npx vercel deploy --prod --token "$VERCEL_TOKEN") \
      && green "Vercel deploy complete" \
      || red "Vercel deploy failed"
  fi
fi

# ─── 5. Render reminder ───
echo ""
echo "=== Render (API) ==="
echo "If not deployed yet:"
echo "  1. Neon: create database warwick_bethel_retreat → paste URL into Render"
echo "  2. Render Dashboard → New → Blueprint → repo PacificLuxeRentals (uses render.yaml)"
echo "  3. Set ConnectionStrings__DefaultConnection = NEON_DATABASE_URL"
echo "  4. Set FRONTEND_URL = ${VERCEL_PRODUCTION_URL:-your Vercel URL}"
echo ""
echo "Health check: curl -s -o /dev/null -w '%{http_code}' ${RENDER_API_URL:-https://warwick-retreat-api.onrender.com}/health"
echo ""

# ─── 6. GitHub Actions secrets reminder ───
echo "=== GitHub Actions (optional CI deploy) ==="
echo "Repository → Settings → Secrets → Actions:"
echo "  VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID"
echo "  NEXT_PUBLIC_API_BASE_URL (for build) = ${RENDER_API_URL:-}"
echo ""

green "Bootstrap script finished."
