// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacificLuxe.Api.Data;

#nullable disable

namespace PacificLuxe.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320162846_AddAdminUsers")]
    partial class AddAdminUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PacificLuxe.Api.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.AvailabilityBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EndDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("EndDateUtc");

                    b.HasIndex("StartDateUtc");

                    b.HasIndex("VehicleId");

                    b.ToTable("availability_blocks", (string)null);
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reservation_id");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("Status");

                    b.HasIndex("ReservationId", "DocumentType")
                        .IsUnique();

                    b.ToTable("driver_documents", (string)null);
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DriverAge")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driver_age");

                    b.Property<DateOnly>("EndDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date_utc");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PickupPreference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("pickup_preference");

                    b.Property<string>("RenterEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("renter_email");

                    b.Property<string>("RenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("renter_name");

                    b.Property<string>("RenterPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("renter_phone");

                    b.Property<DateOnly>("StartDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("EndDateUtc");

                    b.HasIndex("StartDateUtc");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("daily_rate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("HeroImage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("hero_image");

                    b.Property<int>("IncludedMilesPerDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("included_miles_per_day");

                    b.Property<string>("LocationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("location_city");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("trim");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.AvailabilityBlock", b =>
                {
                    b.HasOne("PacificLuxe.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.DriverDocument", b =>
                {
                    b.HasOne("PacificLuxe.Api.Entities.Reservation", "Reservation")
                        .WithMany("DriverDocuments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.Reservation", b =>
                {
                    b.HasOne("PacificLuxe.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("Reservations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.Reservation", b =>
                {
                    b.Navigation("DriverDocuments");
                });

            modelBuilder.Entity("PacificLuxe.Api.Entities.Vehicle", b =>
                {
                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
